name: Docker registry
on:
  workflow_dispatch:


env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_TOKEN: ${{ secrets.docker_token }}
  DISCORD: ${{ secrets.discord_webhook }}

jobs:
  deploy:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ env.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        file: Dockerfile
        push: true
        tags: moleszek/robotframework:latest
        platforms: linux/amd64,linux/arm64
