name: Docker registry
on:
  workflow_dispatch:

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}

jobs:
  deploy:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ env.DOCKER_USER }}
          password: ${{ env.DOCKER_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/robotframework:latest
