name: Docker registry
on:
  release:
    types:
      - published

env:
  DOCKER_USER: ${{ secrets.docker_username }}
  DOCKER_PASS: ${{ secrets.docker_token }}

jobs:
  deploy:
    name: Push docker image to docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check Gecko driver version
        id: version
        run: |
          check=$(curl -s "https://api.github.com/repos/mozilla/geckodriver/releases/latest" | grep '"tag_name":' | sed "s/[^0-9.]//g" | head -n1)
          echo ::set-output name=response::$check
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.docker_username }}
          password: ${{ secrets.docker_token }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          push: true
          tags: moleszek/robotframework:${{ steps.version.outputs.response }}
      #- name: Update docker readme
      #  uses: peter-evans/dockerhub-description@v2
      #  env:
      #    DOCKERHUB_USERNAME: ${{ secrets.docker_username }}
      #    DOCKERHUB_PASSWORD: ${{ secrets.docker_password }}
      #    DOCKERHUB_REPOSITORY: moleszek/robotframework
      #    README_FILEPATH: ./README.md
