name: Test docker image
on:
  push:
    branches:
      - '*'
jobs:
  Check_Image:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docker_robotframework repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Checkout docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: Test docker imgage
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/robotframework
        tag_latest: false
        push: false
        github: true
        token: ${{ secrets.token }}
        owner: ${{ github.repository_owner }}
