name: Test Docker image

on:
  pull_request:
    types: [opened, synchronize, reopened]

env:
  GH_TOKEN: ${{ secrets.token }}

jobs:
  test:
    name: Test Docker image
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build with tag latest
        uses: docker/build-push-action@v6
        with:
          file: Dockerfile
          push: false
          tags: ghcr.io/${{ github.repository }}/robotframework:test
          platforms: ${{ matrix.platform }}
