name: Test docker image
on:
  push:
    branches:
      - '*'
      - '!main'
jobs:
  build_docker_image:
      runs-on: ubuntu-latest
      container: docker:stable
      steps:
      - name: Checkout docker_terraform repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
          ref: main
          token: ${{ secrets.token }}
      - name: Build dockerfile
        run: docker build -t docker-robotframework .
  test_docker_robotframework_version:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout docker_robotframework repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository }}
        ref: main
        token: ${{ secrets.token }}
    - name: Checkout docker_tag repository
      uses: actions/checkout@v2
      with:
        repository: ${{ github.repository_owner }}/docker_tag
        ref: master
        token: ${{ secrets.token }}
        path: .github/actions/docker_tag
    - name: Test docker imgage
      uses: ./.github/actions/docker_tag
      with:
        username: ${{ secrets.docker_username }}
        password: ${{ secrets.docker_token }}
        repository: moleszek/robotframework
        tag_latest: false
        push: false
        github: true
        token: ${{ secrets.token }}
        owner: ${{ github.repository_owner }}
